language: python

sudo: required

python:
  - "3.6"

services: postgresql

before_install:
  - cd code/

env:
  global: 
    - SECRET_KEY="=ws81a&$6hao)i8qy4$h(9ujkwirp%z!==+lx3g=s&garj&h9!"
    - DB_HOST=db
    - DB_USER=postgres
    - DB_PASS=
    - DB_PORT="5432"
    - DB_NAME=postgres
    - ELASTIC_HOST=elasticsearch:9200
    - REDIS_HOST=redis

install:
  - pwd
  - pip install -r $TRAVIS_BUILD_DIR/requirements.txt

before_script:
  - psql -c 'create database postgres;' -U postgres

script: python manage.py test
