language: python

sudo: required

python:
  - "3.6"

services: postgresql

before_install:
  - cd code/

env:
  global: 
    - SECRET_KEY="=ws81a&$6hao)i8qy4$h(9ujkwirp%z!==+lx3g=s&garj&h9!"
    - DB_HOST=localhost
    - DB_USER=postgres
    - DB_PASS=
    - DB_PORT="5432"
    - DB_NAME=postgres
    - ELASTIC_HOST=elasticsearch:9200
    - REDIS_HOST=redis
    - CODECOV_TOKEN="a490d042-d9e1-4c06-b212-8f3893f07331"

install:
  - pwd
  - pip install -r $TRAVIS_BUILD_DIR/requirements.txt

before_script:
  - psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'postgres'" | grep -q 1 || psql -U postgres -c "CREATE DATABASE postgres"

script: 
  - coverage run --source=python manage.py test
  
  
after_success: coveralls
